source 'https://rubygems.org'

gemspec

group :development, :test do
  gem 'rspec', '~> 3.12'
  gem 'rspec-mocks', '~> 3.12'
  gem 'dotenv', '~> 2.8'
  gem 'byebug', '~> 11.1'
  gem 'rubocop', '~> 1.50'
end
